import RevenueChart from "./RevenueChart";
import RevenuePie from "./RevenuePie";

import "../../styles/admin/admin-dashboard.css";

function RevenueSection({ dashboard }) {

    return (

        <div className="analytics-grid">

            <div className="analytics-card analytics-large">

                <div className="card-header">

                    <div>

                        <h3>Revenue by Plan</h3>
                        <p>Revenue generated by each subscription plan</p>

                    </div>

                    <select className="card-select">

                        <option>Last 12 Months</option>

                        <option>Last 6 Months</option>

                        <option>Last 30 Days</option>

                    </select>

                </div>

                <RevenueChart dashboard={dashboard} />

            </div>

            <div className="analytics-card">

                <div className="card-header">

                    <div>

                        <h3>

                            Subscription Distribution

                        </h3>

                        <p>Subscription status distribution</p>

                    </div>

                </div>

                <RevenuePie dashboard={dashboard} />

            </div>

        </div>

    );

}

export default RevenueSection;